---
title: "Vintage Data"
output:
  html_document:
    css: vintage.css
    fig_caption: yes
    highlight: pygments
#  theme: simplex   To have the TOC in Red
    toc: yes
    toc_float: yes
---

This page is being maintained by R. L. Tremblay, PhD. 

Part of the work of preparing the scripts and data entry was performed by undergraduate students at the University of Puerto Rico.  



# Contact Person

### Raymond L. Tremblay, PhD

raymond.tremblay_at_gmail.com

ANALITICA Fundación, Inc




***

# Vintage Data

The following Website brings to life data that we call **Vintage Data**. The objective is to bring data have been available in different published manuscripts for use by Data Scientist and Statistician. The published papers have within the manuscript raw data in form of tables, and these were transferred to Excel Files and are now available for all to use and explore. Since we are interested in papers with raw data included in the manuscript most of the chosen papers are from 1890's to 1910.  Posterior to this period raw dat are rarely include in the published manuscripts.   

We present the raw data as shown in the manuscript and these are appended or linked to a site to download. In addition we add the data files in .csv format.   

We re-construct figures with modern approaches and compare these with the original figures in the manuscript and show these together.   


*** 

## Errors

All data will be available to the public. We have attempted to be careful in transcribing the data and if any errors are found please contact us. The data, concepts and interpretation are does of the authors of the manuscript. 

***

It is our hope that these data can used in Statistical and Data Science exploration and teaching activities.  

***

# Vintage Data Set:

List of Data articles where data set were extracted.
  - Access to the papers are available by selecting the title
  
***  

1. [Birth Weight and Gestation Time in relation to Maternal Age, Parity and Infant Survival](Articles/KARN_et_al-1951-Annals_of_Eugenics.pdf).

This data set pubished in **Annals of Eugenics** in 1951, has data on the birth of 7037 males and 6693 females.  The manuscript is from Mary N Karn and L. S. Penrose from Galton Laboratory.  
 - Karn, M. N., & Penrose, L. S. (1951). Birth weight and gestation time in relation to maternal age, parity and infant survival. Annals of eugenics, 16(1), 147-164.
 
***

2. [Red Blood Cells in tadpoles]
 
 
 



