---
title: "Organized"
author: "Axel Leon"
date: "9/15/2021"
output:
  html_document:
    css: vintage.css
    fig_caption: yes
    highlight: pygments
#  theme: simplex   To have the TOC in Red
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}

Sys.Date()
```

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(ggplot2)
library(gt)
library(reshape)
library(janitor)
library(dplyr)
```

```{r include=FALSE}
#mini=tribble( ~mother_age,~non_survivors,~total_birth,~birth_weight,
#14,0,1,3.5,
#16,1,1,4,
#17,0,1,4.5,
#18,0,2,5,
#19,0,4,6,
#20,0,5,6.5,
#22,3,5,7,
#25,4,10,7.5
#)


T2i <- read_csv("DATA/T2i.csv")


```

```{r echo=FALSE, message=FALSE, warning=FALSE}
df=as.data.frame(T2i)%>%
  mutate(survivors = Count_Total_Birth - Count_Non_survivors)

df1<- untable(df[,c(1,2,4,5)], num = df[,3])%>%
  filter(Count_Non_survivors > 0)%>%
  mutate(dead = ifelse(Count_Non_survivors>=0,0))


df2<- untable(df[,c(1,2,5,4)], num = df[,2])%>%
  filter(survivors >0)%>%
  mutate(Survivors = ifelse(survivors >0, 1))
df3 <- merge(df1, df2)

head(df3)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}

##Utilizar normalized linear model y family = binomial


regr1 <- glm(Mother_age ~ Count_Non_survivors, data = df3, family = binomial)
coefficients(regr1)
summary(regr1)


df3%>%
  ggplot()+
  geom_histogram(aes(survivors), fill= "green", colour="black")
```

